export const THEMES = [
  "Ancient Civilizations",
  "General Human History",
  "Modern Pop Culture",
  "Classic Rock Bands",
  "Famous Scientists",
  "Human Anatomy",
  "American Literature",
  "Greek Mythology",
  "Space Exploration",
  "Famous Inventions",
  "Blockchain and Cryptocurrency",
  "World Cuisine",
  "Famous Artists",
  "Car Brands",
  "Legendary Athletes",
  "Oscar-Winning Movies",
  "Video Game History",
  "Environmental Science",
  "World of Warcraft",
  "Nordic Mythology",
  "Global Economics",
  "Domestic Dogs",
  "Marine Life",
  "Bird Species",
  "Dinosaurs",
  "Endangered Species",
  "Jazz Music",
  "Renaissance Art",
  "Basic Physics",
  "Buddhist Philosophy",
  "Medieval History",
  "Photography Techniques",
  "Fashion Design",
  "Artificial Intelligence",
  "Boxing Champions",
  "Kitchen Appliances",
  "Social Media Platforms",
  "Cybersecurity",
  "Olympic Games",
  "Cocktail Recipes",
  "Architecture Styles",
  "Climate Change",
  "Superhero Movies",
  "Cooking Techniques",
  "Cryptocurrency Mining",
  "Historical Figures",
  "Anime and Manga",
  "Classical Composers",
  "Astronomy",
  "Martial Arts",
  "Web Development",
  "Soccer Teams",
  "Psychology Concepts",
  "Mountain Climbing",
  "Wildlife Photography",
  "Horror Movies",
  "Typography",
  "Board Games",
  "Tropical Fruits",
  "Stand-Up Comedy",
  "Skateboarding",
  "Chemical Elements",
  "Poetry Movements",
  "Cryptocurrency Exchanges",
  "Basketball Players",
  "Interior Design",
  "Mythology Around the World",
  "Machine Learning",
  "Wine Regions",
  "Survival Skills",
  "Digital Marketing",
  "Ancient Egypt",
  "Graphic Design",
  "Documentary Films",
  "Hiking Trails",
  "Genetic Engineering",
  "Podcasts",
  "Surfing",
  "Philosophy Ethics",
  "Technology Startups",
  "Tea Varieties",
  "Robotics",
  "Indie Films",
  "Gardening Tips",
  "Linguistics",
  "Parkour",
  "Memes",
  "Science Fiction Novels",
  "Urban Planning",
  "Cryptocurrency Wallets",
  "Street Fashion",
  "Data Science",
  "Underwater Exploration",
  "Retro Gaming",
  "Jazz History",
  "Esports Teams",
  "Comic Book Heroes",
  "Nature Conservation",
  "Sustainable Living",
  "Virtual Reality",
  "Vinyl Records",
  "Street Art",
  "Motorsports",
  "Herbalism",
  "Film Noir",
  "Woodworking",
  "Space Stations",
  "Fermentation",
  "Heavy Metal Bands",
  "Geology",
  "Meditation Practices",
  "3D Printing",
  "Mythology Symbolism",
  "Streaming Platforms",
];
